# Generated by Django 2.1.15 on 2020-04-06 07:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('billerBillID', models.BigIntegerField(primary_key=True, serialize=False)),
                ('generatedOn', models.DateTimeField()),
                ('recurrence', models.CharField(choices=[('ONE_TIME', 'ONE_TIME'), ('MONTHLY', 'MONTHLY'), ('QUARTERLY', 'QUARTERLY'), ('ANNUALLY', 'ANNUALLY')], default='ONE_TIME', max_length=20)),
                ('amountExactness', models.CharField(choices=[('EXACT', 'EXACT'), ('INEXACT', 'INEXACT')], default='EXACT', max_length=20)),
                ('billAmount', models.IntegerField(default=0)),
                ('paidAmount', models.IntegerField(default=0)),
                ('billPaidFully', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('mobileNumber', models.IntegerField(validators=[django.core.validators.RegexValidator(message='The phone number is not valid', regex='(0/91)?[6-9][0-9]{9}')])),
                ('email', models.CharField(max_length=150)),
                ('userName', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerAccount',
            fields=[
                ('id', models.CharField(db_column='accountId', max_length=50, primary_key=True, serialize=False)),
                ('accountDesc', models.CharField(max_length=250)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='billerRecieptAPI.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('platformBillID', models.CharField(max_length=100)),
                ('platformTransactionRefID', models.CharField(max_length=100)),
                ('uniquePaymentRefID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('amountPaid', models.IntegerField()),
                ('billAmount', models.IntegerField(default=0)),
                ('receiptGenerated', models.BooleanField(default=False)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='bills', to='billerRecieptAPI.Bill')),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('receiptId', models.AutoField(primary_key=True, serialize=False)),
                ('generatedOn', models.DateTimeField(default=django.utils.timezone.now)),
                ('receiptAmount', models.IntegerField(null=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='billerRecieptAPI.Bill')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='billerRecieptAPI.Payment')),
            ],
        ),
        migrations.AddField(
            model_name='bill',
            name='customerAccount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='bills', to='billerRecieptAPI.CustomerAccount'),
        ),
    ]
