# Generated by Django 3.0.5 on 2020-04-03 21:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('billerRecieptAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='generatedOn',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
